name: CI

on:
  push:
    branches: [ main, master, develop, "feature/*", "fix/*" ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [11, 17]
        scala: [2.13.12]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
      with:
        sbt-version: 1.9.7
    
    - name: Cache SBT dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/Dependencies.scala', '**/project/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', '**/project/Dependencies.scala') }}
          ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
          ${{ runner.os }}-sbt-
    
    - name: Compile
      run: sbt compile
    
    - name: Run tests
      run: sbt test
    
    - name: Check code formatting
      run: sbt scalafmtCheckAll || echo "Code formatting check failed - run 'sbt scalafmt' to fix"
    
    - name: Package
      run: sbt package
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-java-${{ matrix.java }}
        path: target/test-reports/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: scala-artifacts-java-${{ matrix.java }}
        path: target/scala-2.13/*.jar
