name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 11
    
    - name: Setup SBT
      uses: sbt/setup-sbt@v1
      with:
        sbt-version: 1.9.7
    
    - name: Cache SBT dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
          ~/.cache/coursier
        key: ${{ runner.os }}-sbt-release-${{ hashFiles('**/build.sbt', '**/project/Dependencies.scala', '**/project/build.properties') }}
        restore-keys: |
          ${{ runner.os }}-sbt-release-
          ${{ runner.os }}-sbt-
    
    - name: Run tests
      run: sbt test
    
    - name: Package application
      run: sbt package
    
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: |
          target/scala-2.13/*.jar
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
